name: Test APIs

on:
  pull_request:
    types: [opened, edited]
    branches:
      - 'main'
      - 'development'
jobs:
  test-apis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v ./...